# Use container-based arch
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: java
jdk:
  - oraclejdk8
  #- oraclejdk7
  #- openjdk7
  - openjdk6

compiler:
  - gcc

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

before_script:
  - ./RebuildNative

cache:
  directories:
  - $HOME/.m2
  - $HOME/.ivy2

deploy:
  - provider: script
    script: travis/docs.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: pages
    local_dir: target/generated-docs
    skip_cleanup: true
    github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
    on:
      branch: master
